version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/usr/src/project
      - ../staticfiles/:/home/project/static/
    ports:
    - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - pgdb

  pgdb:
    image: postgres:13-alpine
    container_name: postgres_db
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    build: ../nginx
    depends_on:
      - django
      - pgdb
    ports:
    - "80:80"
    volumes:
    - ../staticfiles/:/home/project/static/

volumes:
  pgdata:
